/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "#c8c5ca",
        "surface-tint": "#c8c6c8",
        "surface-dim": "#141313",
        "background": "#141313",
        "on-primary-fixed": "#1c1b1d",
        "secondary-fixed": "#e4e1e6",
        "error-container": "#93000a",
        "tertiary-fixed-dim": "#cec4c4",
        "on-secondary-fixed-variant": "#47464a",
        "secondary": "#c8c5ca",
        "surface-container": "#201f1f",
        "secondary-container": "#47464a",
        "tertiary-fixed": "#ebe0df",
        "on-tertiary-fixed-variant": "#4c4545",
        "on-primary-fixed-variant": "#474649",
        "on-tertiary": "#352f2f",
        "on-secondary": "#303033",
        "on-tertiary-container": "#7f7777",
        "on-secondary-container": "#b6b4b8",
        "primary-container": "#09090b",
        "surface-container-high": "#2b2a2a",
        "on-secondary-fixed": "#1b1b1e",
        "primary-fixed": "#e5e1e4",
        "surface-container-lowest": "#0e0e0e",
        "on-primary-container": "#7a787b",
        "on-tertiary-fixed": "#1f1a1a",
        "primary": "#c8c6c8",
        "tertiary-container": "#0c0808",
        "on-background": "#e5e2e1",
        "surface-variant": "#353434",
        "outline": "#919095",
        "inverse-surface": "#e5e2e1",
        "error": "#ffb4ab",
        "inverse-primary": "#5f5e60",
        "on-surface": "#e5e2e1",
        "surface-container-highest": "#353434",
        "surface-bright": "#3a3939",
        "on-error-container": "#ffdad6",
        "surface": "#141313",
        "on-error": "#690005",
        "on-primary": "#313032",
        "inverse-on-surface": "#313030",
        "outline-variant": "#47464a",
        "on-surface-variant": "#c8c5ca",
        "tertiary": "#cec4c4",
        "primary-fixed-dim": "#c8c6c8",
        "surface-container-low": "#1c1b1b",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "stack-sm": "8px",
        "container-padding": "24px",
        base: "4px",
        gutter: "16px",
        "stack-md": "16px",
      },
      fontFamily: {
        "body-md": ["Inter"],
        "label-caps": ["JetBrains Mono"],
        "code-md": ["JetBrains Mono"],
        "body-sm": ["Inter"],
        "headline-sm": ["Inter"],
        "code-sm": ["JetBrains Mono"],
        display: ["Inter"],
      },
      fontSize: {
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-caps": ["11px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" }],
        "code-md": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "body-sm": ["12px", { lineHeight: "18px", fontWeight: "400" }],
        "headline-sm": ["18px", { lineHeight: "28px", fontWeight: "600" }],
        "code-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        display: ["24px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "600" }],
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};
